---
# TODO: clean up with what's not needed
main_folder: '$HOME/Dropbox/.privd'
enc_folder: '$HOME/Dropbox/.privd/enc'
key_email: 'privd@privd.foo'
folders:
  - name: 'main'
    path: '$HOME/.privd/TEST/source'
  - name: 'main_2'
    path: '$HOME/.privd/TEST/source_2'
